---
- name: Install Grafana
  hosts: all
  remote_user: root
  gather_facts: yes
  roles:
  - role: grafana.grafana.grafana
    vars:
      grafana_security:
        admin_user: "{{ GRAFANA_USERNAME }}"
        admin_password: "{{ GRAFANA_PASSWORD }}"
