---

# Install Grafana stack. Documentation at:

# https://grafana.com/docs
# Grafana: https://galaxy.ansible.com/ui/repo/published/grafana/grafana/
# Community: https://docs.ansible.com/ansible/latest/collections/community/grafana/index.html

- name: Manage Grafana Stack
  hosts: all
  remote_user: root
  gather_facts: yes
  roles:
  - role: grafana.grafana.grafana
    name: Manage Grafana
    vars:
      grafana_security:
        admin_user: "{{ GRAFANA_USERNAME }}"
        admin_password: "{{ GRAFANA_PASSWORD }}"
  - role: grafana.grafana.loki
    name: Manage Loki
  # - role: grafana.grafana.tempo
  #   name: Manage Tempo
  - role: grafana.grafana.mimir
    name: Manage Mimir