---
- name: Install and Configure Loki
  hosts: all
  remote_user: root
  gather_facts: no
  pre_tasks:
    - name: Wait for Connection
      ansible.builtin.wait_for_connection:
        delay: 30
        timeout: 60
    - name: Gather Facts
      ansible.builtin.setup:
        
  roles:
    - role: grafana.grafana.loki